Factory/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.Engineers = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    [DisplayName("Name of Thing-a-Machine")]
    public string MachineName { get; set; }
    [DisplayName("Thing-a-Machine Status")]
    public string Status { get; set; }
    [DisplayName("Date of last inspection")]
    [DataType(DataType.Date)]
    public DateTime LastInspection { get; set; }
    public ICollection<EngineerMachine> Engineers { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Factory.Models;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
        .Include(engineer => engineer.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if(MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }


    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      var existingConnection = _db.EngineerMachine.FirstOrDefault(join => join.MachineId == MachineId && join.EngineerId == engineer.EngineerId);

      if(existingConnection != null)
      {
        return RedirectToAction("Details", new {id = engineer.EngineerId});
      }
      if (MachineId != 0)
      {
      _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      List<string> statusList = new List<string>{"Operational", "Malfunctioning", "In repair"};
      ViewBag.StatusTypes = new SelectList(statusList);
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, string StatusTypes)
    {
      machine.Status = StatusTypes;
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
        .Include(machine => machine.Engineers)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine =_db.Machines.FirstOrDefault(machines => machines.MachineId ==id);
      List<string> statusList = new List<string>{"Operational", "Malfunctioning", "In repair"};
      ViewBag.StatusTypes = new SelectList(statusList);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, string StatusTypes)
    {
      machine.Status = StatusTypes;
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine =_db.Machines.FirstOrDefault(machines => machines.MachineId ==id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      var existingConnection = _db.EngineerMachine.FirstOrDefault(join => join.EngineerId == EngineerId && join.MachineId == machine.MachineId);

      if(existingConnection != null)
      {
        return RedirectToAction("Details", new {id = machine.MachineId});
      }
      if (EngineerId != 0)
      {
      _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Add a Imagineer that is licenced to build/repair @Html.DisplayFor(model => model.MachineName)</h1>
<hr/>
  @using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Imagineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<br>
<p>@Html.ActionLink("Back to Thing-a-Machine departement", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Add a new Thing-a-Machine</h2>
<hr/>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.TextBoxFor(model => model.MachineName)
  <br>
  @Html.LabelFor(model => model.Status)
  @Html.DropDownList("StatusTypes")
  <br>
  @Html.LabelFor(model => model.LastInspection)
  @Html.TextBoxFor(model => model.LastInspection, new { type="date"})
  <br>
  <input type="submit" value="Add this Thing-a-Machine" /> <br>
}
<br>
<p>@Html.ActionLink("Back to Thing-a-Maching departement", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Are you sure you want to delete Thing-a-Machine: @Html.DisplayFor(model => model.MachineName)</h1>
<hr/>
@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<br>
<p>@Html.ActionLink("Back to Thing-a-Maching departement", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model Factory.Models.Machine;

<h1>Here are the @Html.DisplayFor(model => model.MachineName)'s details</h1>
<hr/>
<h4>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h4><br>
<h4>@Html.DisplayNameFor(model => model.Status): @Html.DisplayFor(model => model.Status)</h4><br>
<h4>@Html.DisplayNameFor(model => model.LastInspection): @Html.DisplayFor(model => model.LastInspection)</h4>
<br>
@if(@Model.Engineers.Count == 0)
{
  <h4>No Imagineers have yet been licenced to build/repair this Thing-a-Machine yet</h4>
}
else
{
  <h4>Imagineers that are licenced to build/repair this Thing-a-Machine:</h4>
  <br>
  <ul>
  @foreach(var join in Model.Engineers)
  {
    <li>@Html.ActionLink($"{join.Engineer.EngineerName}", "Details", "Engineers", new { id = @join.Engineer.EngineerId })</li>
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      @Html.Hidden("engineerId", "Model.EngineerId")
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<br>
<p>@Html.ActionLink("Add Imagineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Back to Thing-a-Machine departement", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h1>Edit Thing-a-Machine: @Html.DisplayFor(model => model.MachineName)</h1>
<br>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)
  <br>
  @Html.LabelFor(model => model.Status)
  @Html.DropDownList("StatusTypes")
  <br>
  @Html.LabelFor(model => model.LastInspection)
  @Html.EditorFor(model => model.LastInspection, new { type="date"})
  <br>
  <input type="submit" value="Save" />
}
<br>
<p>@Html.ActionLink("Back to Thing-a-Maching departement", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Thing-a-Machines departement</h1>
<hr/>
@if (@Model.Count == 0)
{
  <h3>No Thing-a-Machines have been added yet!</h3>
} 
@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
}
<br>
<p>@Html.ActionLink("Add new Thing-a-Machines", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>